[package]
name = "cargo-fatal"
version = "0.1.0"
authors = ["Alexander Lopatin <alopatindev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
